export const ADD_RESULTS_SUCCESS = 'ADD_RESULTS_SUCCESS'

export const ADD_RESULTS_GET = 'ADD_RESULTS_GET'

export const CREATE_TOKEN = 'CREATE_TOKEN'

export const REFRESH_TOKEN = 'REFRESH_TOKEN'

export const CREATE_CODE = 'CREATE_CODE'

export const CLEAR_LOCAL = 'CLEAR_LOCAL'